version: '3.8'

services:
  db:
    image: postgres:15
    container_name: parking_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: parking_system
    ports:
      - "5432:5432"


# this is to login to the system, not the DB
  pgadmin:  # credentials for admin
    image: dpage/pgadmin4
    container_name: parking_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@test.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    depends_on:
      - db


  pgadmin2: # credentials for the user
    image: dpage/pgadmin4
    container_name: parking_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user2@test.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword2
    ports:
      - "8080:80"
    depends_on:
      - db