-- DROP TABLE IF EXISTS tickets CASCADE;
-- DROP TABLE IF EXISTS payments CASCADE;
-- DROP TABLE IF EXISTS reservations CASCADE;
-- DROP TABLE IF EXISTS permits CASCADE;
-- DROP TABLE IF EXISTS vehicles CASCADE;
-- DROP TABLE IF EXISTS spots CASCADE;
-- DROP TABLE IF EXISTS lots CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS smoke_test2;